export const ATENDEBI_ROLE = {
  ADMIN: 'ATENDEBI_ADMIN',
  DIRETORIA: 'ATENDEBI_DIRETORIA',
  GESTOR: 'ATENDEBI_GESTOR',
  QUALIDADE: 'ATENDEBI_QUALIDADE',
  COMERCIAL: 'ATENDEBI_COMERCIAL',
  ATENDENTE: 'ATENDEBI_ATENDENTE',
} as const;

export type AtendeBIRole = (typeof ATENDEBI_ROLE)[keyof typeof ATENDEBI_ROLE];

export const ATENDEBI_ROLES = Object.values(ATENDEBI_ROLE);

export const PERMISSION_GROUPS = {
  DASHBOARD_READ: [
    ATENDEBI_ROLE.ADMIN,
    ATENDEBI_ROLE.DIRETORIA,
    ATENDEBI_ROLE.GESTOR,
    ATENDEBI_ROLE.QUALIDADE,
    ATENDEBI_ROLE.COMERCIAL,
  ],
  CONVERSATION_READ: [
    ATENDEBI_ROLE.ADMIN,
    ATENDEBI_ROLE.DIRETORIA,
    ATENDEBI_ROLE.GESTOR,
    ATENDEBI_ROLE.QUALIDADE,
    ATENDEBI_ROLE.COMERCIAL,
    ATENDEBI_ROLE.ATENDENTE,
  ],
  OPERATIONS_READ: [
    ATENDEBI_ROLE.ADMIN,
    ATENDEBI_ROLE.DIRETORIA,
    ATENDEBI_ROLE.GESTOR,
    ATENDEBI_ROLE.QUALIDADE,
  ],
  ADMIN_ONLY: [ATENDEBI_ROLE.ADMIN],
} as const;

export function isAtendeBIRole(role: string): role is AtendeBIRole {
  return ATENDEBI_ROLES.includes(role as AtendeBIRole);
}
